[package]
name = "hack-hdsim-cli"
version = "0.0.0"
authors = ["Arseniy Khvorov <khvorov45@gmail.com>"]
edition = "2018"

[dependencies]
hack-hdsim-lib = { path = "../hack-hdsim-lib" }
structopt = "0.3.12"
error-chain = "0.12.2"
